### ISSUE TITLE
[FEAT]: Redis without user/password

### ISSUE THREAD

**Issue by dentatar** [TheNewEconomy/EconomyCore#137]
### Feature Description

Hello, please allow using Redis without these settings. It worked in the past by just commenting them out in data.yml, but i couldn't figure out a way to use it now. I tried empty strings `''` and `~` and `null` nothing worked

### Reasoning

All my servers are in separate network including redis. And redis is only accessible within that network, i personally don't see needs in additional authentication

**Comment by dentatar** [comment]
Sorry, i compiled TNE with commit f958507 and it's not working as expected… Still getting error about login/pass:
```
[00:17:37 ERROR]: Could not pass event PlayerJoinEvent to TheNewEconomy v0.1.3.4
net.tnemc.libs.jedis.jedis.exceptions.JedisAccessControlException: WRONGPASS invalid username-password pair or user is disabled.
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Protocol.processError(Protocol.java:101) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Protocol.process(Protocol.java:162) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Protocol.read(Protocol.java:221) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:350) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.getStatusCodeReply(Connection.java:268) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.helloOrAuth(Connection.java:492) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.initializeFromClientConfig(Connection.java:401) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.<init>(Connection.java:67) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Jedis.<init>(Jedis.java:220) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.JedisFactory.makeObject(JedisFactory.java:170) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.commons.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.commons.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.commons.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.util.Pool.getResource(Pool.java:38) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.JedisPool.getResource(JedisPool.java:378) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.plugincore.core.io.redis.TNEJedisManager.publish(TNEJedisManager.java:82) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.plugincore.core.io.storage.StorageManager.sendProxyMessage(StorageManager.java:97) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.core.channel.SyncHandler.send(SyncHandler.java:47) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.core.handlers.player.PlayerJoinHandler.handle(PlayerJoinHandler.java:200) ~[TNE-BukkitCore.jar:?]
	at TNE-BukkitCore.jar/net.tnemc.bukkit.listeners.player.PlayerJoinListener.onJoin(PlayerJoinListener.java:43) ~[TNE-BukkitCore.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor129.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2233-0d6766e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by creatorfromhell** [comment]
> Sorry, i compiled TNE with commit [f958507](https://github.com/TheNewEconomy/EconomyCore/commit/f958507f38c89aa282e7befa6448aaf175819abb) and it's not working as expected… Still getting error about login/pass:
> 
> ```
> [00:17:37 ERROR]: Could not pass event PlayerJoinEvent to TheNewEconomy v0.1.3.4
> net.tnemc.libs.jedis.jedis.exceptions.JedisAccessControlException: WRONGPASS invalid username-password pair or user is disabled.
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Protocol.processError(Protocol.java:101) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Protocol.process(Protocol.java:162) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Protocol.read(Protocol.java:221) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:350) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.getStatusCodeReply(Connection.java:268) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.helloOrAuth(Connection.java:492) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.initializeFromClientConfig(Connection.java:401) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Connection.<init>(Connection.java:67) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.Jedis.<init>(Jedis.java:220) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.JedisFactory.makeObject(JedisFactory.java:170) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.commons.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.commons.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.commons.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.util.Pool.getResource(Pool.java:38) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.libs.jedis.jedis.JedisPool.getResource(JedisPool.java:378) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.plugincore.core.io.redis.TNEJedisManager.publish(TNEJedisManager.java:82) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.plugincore.core.io.storage.StorageManager.sendProxyMessage(StorageManager.java:97) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.core.channel.SyncHandler.send(SyncHandler.java:47) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.core.handlers.player.PlayerJoinHandler.handle(PlayerJoinHandler.java:200) ~[TNE-BukkitCore.jar:?]
> 	at TNE-BukkitCore.jar/net.tnemc.bukkit.listeners.player.PlayerJoinListener.onJoin(PlayerJoinListener.java:43) ~[TNE-BukkitCore.jar:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor129.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2233-0d6766e]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
> 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
> 	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
> 	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
> ```

What is your config with the compiled jar?

**Comment by dentatar** [comment]
data.yml:
```
Data:
  config-version: '1'
  Sync:
    Type: Redis
    Config:
      SharingPin: 000000
      Sync: false
      Hub: none
      Configs:
      - config.yml
      - messages.yml
      - currency
    Redis:
      Host: ${REDIS_HOST}
      Port: 6379
      #User: user
      #Password: password
      Index: 1
      Timeout: 2000
      SSL: false
      Pool:
        MaxSize: 10
        MaxIdle: 10
        MinIdle: 1
  Purge:
    Enabled: false
    Transaction:
      Archive: true
      Days: 20
    Accounts:
      Days: 90
  Database:
    Type: MySQL
    Prefix: tne_
    File: Economy
    SQL:
      Host: ${DB_HOST}
      SSL: false
      PublicKey: false
      Port: 3306
      DB: TheNewEconomy
      User: TheNewEconomy
      Password: TheNewEconomy
  AutoSaver:
    Enabled: true
    Interval: 600
  Pool:
    MaxSize: 10
    MaxIdle: 10
    MaxLife: 180000
    Timeout: 60000
```
Just commented out redis user and pass, maybe i compiled it wrong tho 🤔

**Comment by creatorfromhell** [comment]
> data.yml:
> 
> ```
> Data:
>   config-version: '1'
>   Sync:
>     Type: Redis
>     Config:
>       SharingPin: 000000
>       Sync: false
>       Hub: none
>       Configs:
>       - config.yml
>       - messages.yml
>       - currency
>     Redis:
>       Host: ${REDIS_HOST}
>       Port: 6379
>       #User: user
>       #Password: password
>       Index: 1
>       Timeout: 2000
>       SSL: false
>       Pool:
>         MaxSize: 10
>         MaxIdle: 10
>         MinIdle: 1
>   Purge:
>     Enabled: false
>     Transaction:
>       Archive: true
>       Days: 20
>     Accounts:
>       Days: 90
>   Database:
>     Type: MySQL
>     Prefix: tne_
>     File: Economy
>     SQL:
>       Host: ${DB_HOST}
>       SSL: false
>       PublicKey: false
>       Port: 3306
>       DB: TheNewEconomy
>       User: TheNewEconomy
>       Password: TheNewEconomy
>   AutoSaver:
>     Enabled: true
>     Interval: 600
>   Pool:
>     MaxSize: 10
>     MaxIdle: 10
>     MaxLife: 180000
>     Timeout: 60000
> ```
> 
> Just commented out redis user and pass, maybe i compiled it wrong tho 🤔

When testing locally, it isn't passing the user/pass to the jedis library. You restarted after commenting out?

**Comment by dentatar** [comment]
Yes… Whatever, thank you, i'll wait for release build

**Comment by creatorfromhell** [comment]
> Yes… Whatever, thank you, i'll wait for release build

I'll test locally again, could be a difference in the setup I had, or I'll add a bypass configuration option for each. Not sure what the "whatever" is here.

**Comment by creatorfromhell** [comment]
[TNE-BukkitCore-0.1.3.4-Release-1.zip](https://github.com/user-attachments/files/17984585/TNE-BukkitCore-0.1.3.4-Release-1.zip)


> Yes… Whatever, thank you, i'll wait for release build

Try this jar, leave the User and Password field uncommented and set both to "none"
