### ISSUE TITLE
[BUG]: Unable to use Towny commands after switching to the rewrite

### ISSUE THREAD

**Issue by r0xANDt0l** [TheNewEconomy/EconomyCore#47]
### TNE Version

0.1.20.0-PRE-8

### Spigot Version

1.19.4

### Your config.yml

https://paste.ee/p/Pa0WH

### Your latest server log

https://mclo.gs/jQreD1N

### What part of TNE is the bug affecting?

Towny Support

### Is your server using online mode?

No

### Bug description

When you try to run a towny command, for example `/town`, it doesn't show anything on screen and shows and error on console (check logs)

### How to reproduce

1. Switch to rewrite
2. Try to use towny commands
3. See error

**Comment by creatorfromhell** [comment]
See previous response.

**Comment by r0xANDt0l** [comment]
Still happens after deleting config.yml and rewriting every config from scratch
```
[00:07:42 WARN]: [Towny] Plugin Towny v0.99.2.4 generated an exception while executing task 63395
java.util.NoSuchElementException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1599) ~[?:?]
        at java.util.HashMap$ValueIterator.next(HashMap.java:1625) ~[?:?]
        at net.tnemc.core.manager.CurrencyManager.getDefaultCurrency(CurrencyManager.java:152) ~[BukkitCore-0.1.2.0-PRE-8.jar:?]
        at net.tnemc.bukkit.hook.economy.TNEVault.getBalance(TNEVault.java:189) ~[BukkitCore-0.1.2.0-PRE-8.jar:?]
        at net.tnemc.bukkit.hook.economy.TNEVault.getBalance(TNEVault.java:167) ~[BukkitCore-0.1.2.0-PRE-8.jar:?]
        at com.palmergames.bukkit.towny.object.economy.adapter.VaultEconomyAdapter.getBalance(VaultEconomyAdapter.java:33) ~[towny-0.99.2.4.jar:?]
        at com.palmergames.bukkit.towny.TownyEconomyHandler.getBalance(TownyEconomyHandler.java:155) ~[towny-0.99.2.4.jar:?]
        at com.palmergames.bukkit.towny.object.economy.BankAccount.getHoldingBalance(BankAccount.java:122) ~[towny-0.99.2.4.jar:?]
        at com.palmergames.bukkit.towny.object.economy.Account.getHoldingBalance(Account.java:175) ~[towny-0.99.2.4.jar:?]
        at com.palmergames.bukkit.towny.object.economy.BankAccount.getHoldingFormattedBalance(BankAccount.java:133) ~[towny-0.99.2.4.jar:?]
        at com.palmergames.bukkit.towny.TownyFormatter.addTownMoneyComponents(TownyFormatter.java:782) ~[towny-0.99.2.4.jar:?]
        at com.palmergames.bukkit.towny.TownyFormatter.getStatus(TownyFormatter.java:344) ~[towny-0.99.2.4.jar:?]
        at com.palmergames.bukkit.towny.command.TownCommand.lambda$townStatusScreen$35(TownCommand.java:4248) ~[towny-0.99.2.4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by creatorfromhell** [comment]
Could you upload your log with the debug mode set to developer?  From start to error?

**Comment by r0xANDt0l** [comment]
https://mclo.gs/FtiSZ3D
